# Generated by Django 4.2.1 on 2023-05-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Faculties configured'),
        ),
    ]
