# Generated by Django 4.2.1 on 2023-05-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_school_is_activated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('school', 'name')},
        ),
    ]
