# Generated by Django 4.2.1 on 2023-05-20 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='change',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('a', 'awarded'), ('b', 'deducted')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='action',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.house'),
        ),
        migrations.AlterField(
            model_name='action',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
