# Generated by Django 4.2.1 on 2023-05-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_action_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('a', 'award'), ('b', 'deduct')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='action',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
