# Generated by Django 4.2.1 on 2023-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_alter_action_action_type_alter_action_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
